#!/bin/mksh

# Env vars 
. "$HOME/.config/mksh/profile"

alias fm="ranger"

# Editor aliases
alias \
	v="$EDITOR" \
	e="$EDITOR" \
	vmksh="$EDITOR $XDG_CONFIG_HOME/mksh/mkshrc" \
	val="$EDITOR $XDG_CONFIG_HOME/mksh/aliasrc" \
	vcon="$EDITOR config.h" 

# Nix aliases
alias \
	alias rebuild='nh os switch --flake /home/png76/nixos#snow' \
	alias nix-clean='nh clean all && nix store optimise' 

alias please='sudo $(fc -ln -1)'

PS1='${PWD/#$HOME/"~"} $ '

# History
HISTFILE="$XDG_DATA_HOME/history"
HISTSIZE=1000000

lfcd() {
	tmp="$(mktemp)"
	lf -last-dir-path="$tmp" "$@"
	if [ -f "$tmp" ]; then
		dir="$(cat "$tmp")"
		rm -f "$tmp" >/dev/null
		[ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
	fi
}

# Calculator 
alias calc='bc -lq'
fzfcd() { cd "$(dirname "$(fzf)")"; }

# Stopwatch and countdown 
countdown() {
	start="$(( $(date '+%s') + $1 ))"
	while [ "$start" -ge "$(date +%s)" ]; do
		time="$(( start - $(date +%s) ))"
		printf '%s\r' "$(date -u -d "@$time" +%H:%M:%S)"
		sleep 0.1
	done
}

stopwatch() {
	start=$(date +%s)
	while true; do
		time="$(( $(date +%s) - start ))"
		printf '%s\r' "$(date -u -d "@$time" +%H:%M:%S)"
		sleep 0.1
	done
}

# PATH
export PATH="$HOME/.local/bin:$PATH"

# ============================
# Interactive-only console I/O
# ============================
if [[ -t 0 ]]; then
	stty stop undef
	echo -ne '\e[5 q'   
fi


